"""ORM models. Import every model here so ``Base.metadata`` is complete for Alembic."""

from app.models.auth import (
    AuthEvent,
    AuthEventType,
    AuthIdentity,
    OAuthState,
    OtpCode,
    UserSession,
)
from app.models.chat import MESSAGE_MAX_LENGTH, Message
from app.models.jobs import EmailLog, EmailPurpose, Job, JobStatus, RateLimitCounter
from app.models.matching import (
    INTENTS,
    REQUEST_TEXT_MAX_LENGTH,
    REQUEST_TEXT_MIN_LENGTH,
    Match,
    MatchRequest,
    MatchStatus,
    RequestStatus,
)
from app.models.moderation import (
    REPORT_CONTEXT_MESSAGES,
    REPORT_DETAILS_MAX_LENGTH,
    REPORT_NOTE_MAX_LENGTH,
    Block,
    ModerationAction,
    ModerationActionKind,
    Report,
    ReportReason,
    ReportStatus,
    ReportTarget,
)
from app.models.profile import (
    ABOUT_TEXT_MAX_LENGTH,
    DISPLAY_NAME_MAX_LENGTH,
    LINK_MAX_LENGTH,
    MAX_LANGUAGES,
    MAX_LINKS,
    ParseSource,
    ParseStatus,
    Profile,
    ProfileVisibility,
)
from app.models.profile_embedding import EMBEDDING_DIMENSIONS, EmbeddingFacet, ProfileEmbedding
from app.models.social import (
    INTRO_NOTE_MAX_LENGTH,
    Connection,
    Intro,
    IntroStatus,
    Notification,
    NotificationKind,
)
from app.models.user import EMAIL_MAX_LENGTH, AuthProvider, User, UserStatus

__all__ = [
    "ABOUT_TEXT_MAX_LENGTH",
    "DISPLAY_NAME_MAX_LENGTH",
    "EMAIL_MAX_LENGTH",
    "EMBEDDING_DIMENSIONS",
    "INTENTS",
    "INTRO_NOTE_MAX_LENGTH",
    "LINK_MAX_LENGTH",
    "MAX_LANGUAGES",
    "MAX_LINKS",
    "MESSAGE_MAX_LENGTH",
    "REPORT_CONTEXT_MESSAGES",
    "REPORT_DETAILS_MAX_LENGTH",
    "REPORT_NOTE_MAX_LENGTH",
    "REQUEST_TEXT_MAX_LENGTH",
    "REQUEST_TEXT_MIN_LENGTH",
    "AuthEvent",
    "AuthEventType",
    "AuthIdentity",
    "AuthProvider",
    "Block",
    "Connection",
    "EmailLog",
    "EmailPurpose",
    "EmbeddingFacet",
    "Intro",
    "IntroStatus",
    "Job",
    "JobStatus",
    "Match",
    "MatchRequest",
    "MatchStatus",
    "Message",
    "ModerationAction",
    "ModerationActionKind",
    "Notification",
    "NotificationKind",
    "OAuthState",
    "OtpCode",
    "ParseSource",
    "ParseStatus",
    "Profile",
    "ProfileEmbedding",
    "ProfileVisibility",
    "RateLimitCounter",
    "Report",
    "ReportReason",
    "ReportStatus",
    "ReportTarget",
    "RequestStatus",
    "User",
    "UserSession",
    "UserStatus",
]
